<a href="https://colab.research.google.com/github/Taheri1400/deep-learning-projects/blob/main/play_with_shallow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
کم‌عمق بازی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه </font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
به یک تمرین اساسی از پایه‌ای‌ترین مباحث شبکه‌های عصبی خوش آمدید! 🤖 در این تمرین قصد داریم ساختار شبکه‌ی عصبی و الگوریتم آموزش آن را که در درسنامه‌های پیشین آموختید، از پایه پیاده‌سازی کنیم. کدنویسی در این سطح به شما کمک خواهد کرد که به‌شکل عملی، درک عمیق‌تری از نحوه‌ی کار این مدل پیدا کنید و در آینده نیز هنگام مواجهه با مدل‌های مختلف شبکه‌های عصبی قادر به تحلیل آسان‌تر ساختار آن‌ها باشید. در این تمرین پس از طراحی کامل یک <b>شبکه‌ی عصبی کم‌عمق (Shallow Neural Network)</b>، آن را روی مجموعه‌داده‌ی مشهور <b>دیابت پیما ایندیانز (Pima Indians Diabetes)</b> آموزش داده و عملکرد مدل را بر روی این مجموعه‌داده ارزیابی خواهیم کرد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیاز را وارد کنید. دقت کنید که در این تمرین مجاز به استفاده از کتابخانه‌هایی به‌جز موارد موجود در نت‌بوک نیستید.
</font>
</p>

In [3]:
import numpy as np
import pandas as pd

In [2]:
!pip install keras --upgrade

Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (3.15.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras) (0.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from optree->keras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این تمرین از مجموعه‌‌داده‌ی ساده اما مشهور <b>دیابت پیما ایندیانز (Pima Indians Diabetes)</b>
استفاده خواهیم کرد. این مجموعه‌داده شامل اطلاعات مربوط به ۷۶۸ زن بومی آمریکا از قبیله‌ی پیما است که برای بررسی عوامل خطر  ابتلا به دیابت نوع ۲ جمع‌آوری شده است. این اطلاعات شامل سن، وزن، قد، سابقه‌ی خانوادگی دیابت، فشار خون، سطح گلوکز خون و سایر عوامل می‌شود.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Pregnancies</code>|تعداد بارداری های فرد|
|<code>Glucose</code>|سطح گلوکز خون (<code dir=ltr>mg/dL</code>)|
|<code>BloodPressure</code>|فشار خون سیستولیک (<code>mmHg</code>)|
|<code>SkinThickness</code>|ضخامت پوست (<code dir=ltr>mm</code>) |
|<code>Insulin</code>|سطح انسولین خون (<code dir=ltr>μU/mL</code>) |
|<code>BMI</code>|شاخص توده بدنی (<code dir=ltr>kg/m^2</code>) |
|<code>DiabetesPedigreeFunction</code>|تابعی بیانگر سابقه‌ی خانوادگی دیابت|
|<code>Age</code>|سن زن (سال) |
|<code>Outcome</code>|عدم ابتلا (<code>0</code>) یا ابتلا (<code>1</code>) به دیابت|

</font>
</div>
</center>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خوانش مجموعه‌داده
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
   در ابتدا نیاز است فایل‌ مجموعه‌داده را بخوانید. داده‌‌های آموزش را می‌توانید از فایل <code>diabetes_train.csv</code> موجود در پوشه‌ی <code>data</code> بخوانید و از نمونه‌های موجود در آن برای آموزش مدل استفاده کنید.
 عملکرد مدل شما روی داده‌ی <code>diabetes_test.csv</code> بررسی می‌شود که از نظر ساختار مانند داده‌های آموزش است با این تفاوت که ستون <code>Outcome</code> از آن حذف شده‌است.
</font>
</p>

In [20]:
train_data = pd.read_csv('diabetes_train.csv')
train_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [21]:
test_data = pd.read_csv('diabetes_test.csv')
test_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,98,58,33,190,34.0,0.430,43
1,9,154,78,30,100,30.9,0.164,45
2,6,165,68,26,168,33.6,0.631,49
3,1,99,58,10,0,25.4,0.551,21
4,10,68,106,23,49,35.5,0.285,47

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 ابتدا ستون متغیر هدف (<code>Outcome</code>) را در یک دیتافریم دیگر ذخیره کنید و سپس این ستون را از دیتافریم <code>train_data</code> حذف کنید تا ماتریس معادل $X$ و $y$ ساخته شوند.</font>
</p>

In [22]:
train_data_outcome = train_data['Outcome']
train_data = train_data.drop(columns='Outcome')

train_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 یکی از اعمال مهم پیش‌پردازش، تغییر مقیاس ویژگی‌ها به‌صورت توزیع نرمال است که اصطلاحاً به آن نرمال‌سازی (Normalization) می‌گوییم.
 نرمال‌سازی به کاهش تغییرات شدید در وزن‌ها کمک کرده و باعث سرعت بالاتر همگرایی مدل می‌شود.
برای انجام نرمال‌سازی در این تمرین باید اعداد هر ویژگی را طوری تغییر دهیم که میانگین آن‌ها <code>0</code> شود و واریانس <code>1</code> داشته باشند، این‌کار را می‌توانیم با استفاده از فرمول زیر انجام دهیم.
برای سری داده‌ی <code>X</code> (که در اینجا مقادیر هر ستون می‌باشد) به طوری‌که <code>X = [x_1, x_2, ..., x_n]</code>، با کم کردن میانگین از هر نمونه‌ی داده (<code>x_i</code>) و تقسیم آن بر انحراف معیار داده‌ها (سیگما) می‌توانیم سری داده‌ی نرمال‌شده را به‌دست آوریم.
</font>
</p>

$$ Z = \frac{x_i - \bar{x}}{\sigma} $$

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
دقت داشته باشید، از آنجا که در واقع ما فقط اطلاعات مربوط به مجموعه‌داده‌ی آموزش را در هنگام ساخت مدل داریم، برای نرمال‌سازی نمونه‌های آزمون نیز باید از میانگین و انحراف معیار نمونه‌های آموزش استفاده کنیم.
</font>
</p>

In [23]:
for column in train_data.columns:
  mean =train_data[column].mean()
  std = train_data[column].std()
  train_data[column]=(train_data[column]- mean)/std
  test_data[column]=(test_data[column] - mean)/std

train_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.649833,0.854539,0.166518,0.900880,-0.687695,0.222281,0.438405,1.443781
1,-0.835754,-1.096441,-0.140758,0.526362,-0.687695,-0.672046,-0.370035,-0.178571
2,1.244068,1.938416,-0.243184,-1.283807,-0.687695,-1.093658,0.570216,-0.093184
3,-0.835754,-0.972569,-0.140758,0.151844,0.123855,-0.480405,-0.908995,-1.032441
4,-1.132872,0.513891,-1.472290,0.900880,0.762734,1.436011,5.303692,-0.007797

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
حال مقدار بایاس را به دیتافریم اضافه می‌کنیم. برای این‌کار باید یک ستون با مقدار <code>1</code> به ابتدای مجموعه‌‌داده اضافه کنیم.
</font>
</p>

In [24]:
train_bias =  np.ones((len(train_data),1))
train_bias=pd.DataFrame(train_bias, columns=['Bias'])
train_data =  pd.concat([train_bias,train_data],axis=1)

test_bias = np.ones((len(test_data),1))
test_bias=pd.DataFrame(test_bias, columns=['Bias'])
test_data = pd.concat([test_bias,test_data],axis=1)

train_data.head()

,Bias,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1.0,0.649833,0.854539,0.166518,0.900880,-0.687695,0.222281,0.438405,1.443781
1,1.0,-0.835754,-1.096441,-0.140758,0.526362,-0.687695,-0.672046,-0.370035,-0.178571
2,1.0,1.244068,1.938416,-0.243184,-1.283807,-0.687695,-1.093658,0.570216,-0.093184
3,1.0,-0.835754,-0.972569,-0.140758,0.151844,0.123855,-0.480405,-0.908995,-1.032441
4,1.0,-1.132872,0.513891,-1.472290,0.900880,0.762734,1.436011,5.303692,-0.007797

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 قبل از طراحی و آموزش مدل ابتدا باید مجموعه‌داده را از حالت دیتافریم به آرایه‌ی <code>numpy</code> کنیم. بنابراین در این مرحله دیتافرم‌های <code>train_data</code> ،<code>train_data_outcome</code>  را تبدیل به آرایه‌های <code>numpy</code> کنید.
 همچنین به‌کمک تابع <code>train_test_split</code> این مجموعه‌داده را با نسبت <code>0.2</code> به دو بخش آموزش و اعتبارسنجی تقسیم کنید.
<br>
    توجه کنید که با توجه به درسنامه‌ی پیشین هر <b>سطر</b> از ماتریس ورودی نشان دهنده‌ی یک <b>ویژگی</b> و هر <b>ستون</b> نشان دهنده‌ی یک <b>نمونه</b> است، بنابراین در این مرحله نیاز است ماتریس ویژگی‌ها را ترانهاده کنید. این عمل برای متغیر هدف یا <code>train_data_outcome</code> نیز باید انجام گردد.
</font>
</p>

In [25]:
from sklearn.model_selection import train_test_split
X=train_data.to_numpy()
y=train_data_outcome.to_numpy()
test_data_numpy=test_data.to_numpy()
X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2)

X_train =X_train.T
X_validation = X_validation.T
y_train = y_train.T
y_validation = y_validation.T
test_data_numpy = test_data_numpy.T

In [26]:
test_data_numpy.shape

(9, 100)

   <p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
برای اطمینان از درستی تنظیمات ورودی و خروجی مدل، با اجرای سلول بعد باید به خروجی زیر برسید.
     </p>

```
X_train.shape:(9, 534), y_train.shape:(534,)
X_validation.shape:(9, 134), y_validation.shape:(134,)
test_data_numpy.shape:(9, 100)
```

In [27]:
print(f'X_train.shape:{X_train.shape}, y_train.shape:{y_train.shape}')
print(f'X_validation.shape:{X_validation.shape}, y_validation.shape:{y_validation.shape}')
print(f'test_data_numpy.shape:{test_data_numpy.shape}')

X_train.shape:(9, 534), y_train.shape:(534,)
X_validation.shape:(9, 134), y_validation.shape:(134,)
test_data_numpy.shape:(9, 100)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    اکنون که داده‌ها را پردازش و آماده کردید نوبت به قسمت اصلی یعنی ساخت مدل می‌رسد. در اینجا از شما خواسته شده تا یک مدل ساده‌ی کم‌عمق را با روش نزول گرادیان از صفر پیاده کنید. برای این کار قدم به قدم هر جزء این مدل را شرح خواهیم داد تا نسبت به پیاده‌‌سازی آن اقدام کنید.
    <br>
این مدل یک شبکه‌ی عصبی کم‌عمق با یک لایه‌ی پنهان با <code>1000</code> نورون می‌باشد، همچنین تابع فعال‌ساز این لایه، تابع فعال‌ساز یکسوساز (<code>ReLU</code>) می‌باشد که در درسنامه‌ی تابع ‌فعال‌ساز با آن آشنا شدید. همچنین تابع فعال‌ساز لایه‌ی خروجی تابع سیگموید (<code>sigmoid</code>) می‌باشد. توجه کنید فرمول‌های مورد نیاز هر بخش در ادامه آمده است. دو تابع فعال‌ساز مورد نظر را در ادامه پیاده‌سازی کرده‌ایم.
</font>
</p>

<center>

```python
sigmoid_Z = 1 / (1 + np.exp(-Z)
```

```python
ReLU_Z = np.maximum(0, Z)
```

</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
<br>
    <span style="color:orange"><b>نکته: </b></span>
    در اعمال ریاضی و محاسباتی خود تنها از کتابخانه‌ی نامپای استفاده کنید و لیست‌های خود را نیز به شکل آرایه‌ی نامپای تعریف کنید.
    <br>
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <span style="color:purple"><b>یادآوری: </b></span>
    تابع سیگموید
</font>
</p>

<center>
<div dir=ltr style="direction: ltr;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| تابع سیگموید | مشتق تابع سیگموید |
| :---: | :--: |
|$f(z) = \frac{1}{1 + e^{-z}}$|$f'(z) =f(z)(1-f(z))$|

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <span style="color:purple"><b>یادآوری: </b></span>
    تابع یکسوساز (ReLU)
</font>
</p>

<center>
<div dir=ltr style="direction: ltr;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| تابع یکسوساز  | مشتق تابع  یکسوساز  |
| :---: | :--: |
|$$f(z) = \begin{cases} 0 & \text{if } z < 0 \\ z & \text{if } z \geq 0\end{cases}$$|$$f'(z) = \begin{cases} 0 & \text{if } z < 0 \\ 1 & \text{if } z \geq 0\end{cases}$$|

</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
   <code>Model</code> ساخت کلاس
</font>
</h2>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
در این قسمت باید یک کلاس با نام <code>Model</code>  بسازید که دارای سه تابع زیر است. در ادامه به شرح جزئیات هر تابع می‌پردازیم.
</p>
</font>

```python
def __init__(self)
def predict(self, inputs)
def update_weights_for_one_epoch(self, inputs, outputs, learning_rate)
def fit(self, inputs, outputs, learning_rate, epochs=64)
```

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
   <code>__init__</code> تابع
</font>
</h3>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در تابع <code>__init__(self)</code> وزن‌های اولیه لایه‌های پنهان و خروجی (<code>w1</code> و <code>w2</code>) را به‌صورت تصادفی با میانگین <code>0</code> و انحراف معیار <code>0.01</code> مقداردهی کنید. برای این کار می‌توان از تابع <code>np.random.randn</code> استفاده کرد. البته توجه داشته باشید تابع <code>np.random.randn</code> اعداد تصادفی با میانگین <code>0</code> و انحراف معیار <code>1</code> تولید می‌کند، بنابراین نیاز است مطابق خواسته‌ی مسئله این مقادیر را کمی تغییر دهید.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
   <code>predict</code> تابع
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
تابع <code>predict(self, inputs)</code> با گرفتن ورودی‌ها، به‌ترتیب خروجی‌ هر دو لایه (<code>A_1</code> و <code>A_2</code>) را باز می‌گرداند.
این عمل را مطابق فرمول‌های زیر انجام دهید.
</font>
</p>

$$Z^{[1]}=W^{[1]}.X$$
$$A^{[1]}=ReLU(Z^{[1]})$$
$$Z^{[2]}=W^{[2]}A^{[1]}$$
$$A^{[2]}=\sigma(Z^{[2]})=\frac{1}{1+e^{-Z^{[2]}}}=Y_{pred}$$

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
برای پیاده سازی ضرب ماتریسی دو ماتریس از تابع <code>(arr1.dot(arr2</code>
 استفاده کنید. به‌طور مثال فرمول $Z^{[1]}=W^{[1]}X$ در پایتون مطابق <code> (W_1.dot(X </code>
 است.
    همچنین می‌توانید از عملگر  <code> @ </code> نیز به‌صورت <code> W_1 @ X</code> استفاده کنید.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
   <code>update_weights_for_one_epoch</code> تابع
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در تابع <code>(update_weights_for_one_epoch(self, inputs, outputs, learning_rate</code> باید وزن‌های شبکه را برای یک <code>epoch</code> به‌روزرسانی کنید. توجه داشته باشید مقدار <code>learning_rate</code> همان نرخ یادگیری یا آلفا است . فرمول‌های مورد نیاز برای این بخش در زیر آورده شده است. در فصل بعد جزئیات نحوه‌ی محاسبه‌ی آن‌ها را شرح داده‌ایم.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
نحوه به‌روزرسانی <code>w2</code> به شرح زیر می‌باشد:
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
<span style="color:orange"><b>نکته:</b></span>
دقت داشته باشید نماد $\odot$ ضرب درآیه‌ای می‌باشد و نماد $\bullet$ ضرب ماتریسی است.
</font>
</p>
                                                                                     
$$W^{[2]} = W^{[2]} + \Delta W^{[2]}$$
$$\Delta W^{[2]} = - \alpha \frac{\partial cost}{\partial W^{[2]}}$$
$$\frac{\partial cost}{\partial W^{[2]}} = (\frac{-2}{n}(Y_{true}-A^{[2]})\odot A^{[2]}\odot (1-A^{[2]}))\bullet A^{[1]T}$$
$$W^{[2]}=W^{[2]}+(\frac{2 \alpha}{n}(Y_{true}-A^{[2]})\odot A^{[2]}\odot (1-A^{[2]}))\bullet A^{[1]T}$$

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
نحوه به‌روزرسانی <code>w1</code> به شرح زیر می‌باشد:
</font>
</p>

$$W^{[1]} = W^{[1]} + \Delta W^{[1]}$$
$$\Delta W^{[1]} = - \alpha \frac{\partial cost}{\partial W^{[1]}}$$

$$\frac{\partial cost}{\partial W^{[1]}} = (((\frac{-2}{n}(Y_{true}-A^{[2]})\odot A^{[2]}\odot (1-A^{[2]}))^T\bullet W^{[2]})^T\odot \frac{\partial A^{[1]}}{\partial Z^{[1]}}) \bullet X^T$$

$$W^{[1]}=W^{[1]}+(((\frac{2 \alpha}{n}(Y_{true}-A^{[2]})\odot A^{[2]}\odot (1-A^{[2]}))^T\bullet W^{[2]})^T\odot \frac{\partial A^{[1]}}{\partial Z^{[1]}}) \bullet X^T$$


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای به‌دست‌آوردن مقدار $\frac{\partial A^{[1]}}{\partial Z^{[1]}}$ که همان مشتق تابع یکسوساز می‌باشد از قطعه کد زیر استفاده کنید که خروجی آن یک ماتریس با اندازه‌ای برابر با اندازه‌ی $Z^{[1]}$ و متشکل از <code>0</code> و <code>1</code> است، به‌طوری که متناظر با سلول‌هایی که مقدار $Z^{[1]}$ در آن بیشتر از صفر است، مقدار <code>1</code> و در غیر این‌صورت مقدار <code>0</code> دارد. البته به علت نحوه‌ی کد زدن مدل ورودی این تابع را <code>A_1</code> می‌دهیم اما در خروجی تابع تفاوتی ندارد (چرا؟).
</font>
</p>

<center>

```python
relu_gradient = np.where(A_1 > 0, 1, 0)
```

</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 توجه داشته باشید بخشی از $\Delta W^{[1]}$ در $\Delta W^{[2]}$ محاسبه شده است که می‌توان با نگه‌داری آن از محاسبه‌ی اضافی جلوگیری کنیم.

</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
   <code>fit</code> تابع
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 تابع <code>fit(self, inputs, outputs, learning_rate, epochs=64)</code> به تعداد دور‌های مشخص‌شده (<code>epochs</code>) وزن‌های شبکه را به‌روزرسانی می‌کند. نیازی نیست در این تابع نیازی تغییری ایجاد کنید و کافیست در مراحل بعدی از آن استفاده کنید.

</font>
</p>

In [28]:
X_train.shape

(9, 534)

In [29]:
class Model:

    def __init__(self):

        self.w1 = np.random.randn(1000,9)*0.01
        self.w2 = np.random.randn(1,1000)*0.01

    def predict(self, inputs):
        x = inputs

        Z_1 = self.w1.dot(x)
        A_1 = np.maximum(0, Z_1)

        Z_2 = self.w2.dot(A_1)
        A_2 = 1 / (1 + np.exp(-Z_2))

        return A_1, A_2

    def update_weights_for_one_epoch(self, inputs, outputs, learning_rate):
        x, y_true = inputs, outputs
        A_1, A_2 = self.predict(inputs)

        n = x.shape[1]

        shared_coefficient =  2 * learning_rate / n * ((y_true - A_2) * A_2 * (1 - A_2))
        relu_gradient = np.where(A_1 > 0, 1, 0)

        self.w1 = self.w1 + (((shared_coefficient.T @ self.w2).T * relu_gradient) @ x.T)
        self.w2 = self.w2 + shared_coefficient @ A_1.T

    def fit(self, inputs, outputs, learning_rate, epochs=64):
        for i in range(epochs):
            self.update_weights_for_one_epoch(inputs, outputs, learning_rate)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش و بررسی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
    پس از طراحی ساختار شبکه می‌توانید به کمک <code dir=ltr>Model()</code> ابتدا یک شیء از این کلاس بسازید و سپس تابع <code>fit</code> را با آرگومان‌های مناسب صدا بزنید تا آموزش مدل آغاز شود. پیشنهاد می‌شود مقادیر مختلف نرخ یادگیری (مانند <code>0.1</code>، <code>0.01</code>، <code>0.001</code> و...) و همچنین تعداد دور‌های آموزش متفاوت را آزمایش کرده و نتیجه را روی نمونه‌های اعتبارسنجی مقایسه کنید.
برای بررسی دقت مدل می‌توانید از تابع <code dir=ltr>evaluation(model, inputs, outputs)</code> استفاده کنید.

</font>
</p>

In [30]:
def evaluation(model, inputs, outputs):
  _, A_2 = model.predict(inputs)
  prediction = (A_2 > 0.5)
  return np.mean(prediction == outputs) * 100

In [31]:
model = Model()
model.fit(X_train, y_train, learning_rate = 0.01, epochs = 64)

# Model evaluation
print(f"you model accuracy on given set: {round(evaluation(model, X_validation, y_validation), 2)}%") # TODO

you model accuracy on given set: 80.6%

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌بینی برای داده آزمون و خروجی
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
در نهایت باید خروجی مدل خود را برای نمونه‌های آزمون محاسبه کنید. برای این‌کار ابتدا خروجی مدل را روی داده‌ی آزمون به‌دست آورید و سپس اگر مدل احتمال بیشتری دهد که فرد دیابت داشته باشد (خروجی بیشتر از <code>0.5</code>) آن فرد را دارای دیابت پیش‌بینی می‌کنیم و در غیر این‌صورت آن فرد را بدون دیابت پیش‌بینی می‌کنیم.
<br>بنابراین در متغیر <code>prediction</code> که از جنس یک آرایه‌ی نامپای است، مقادیر <code>True</code> و <code>False</code> خواهیم داشت، دقت کنید این متغیر نیز در سیستم داوری مورد بررسی قرار خواهد گرفت.
</font>
</p>

In [32]:
_ , output= model.predict(test_data_numpy) # TODO
prediction = output>0.5

In [33]:
prediction

array([[False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False,  True, False,  True,  True,  True, False,
        False, False, False,  True,  True, False, False,  True,  True,
        False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
         True, False, False,  True,  True,  True,  True,  True,  True,
        False,  True, False, False,  True, False,  True,  True, False,
        False, False, False,  True, False,  True, False, False, False,
        False]])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نحوه‌ی داوری تمرین
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در نهایت، در این تمرین هر کدام از توابعی که پیاده کرده‌اید به‌صورت جداگانه مورد داوری قرار خواهد گرفت تا از عملکرد هر کدام به شکل جداگانه مطمئن شوید. دقت مدل شما روی داده‌ی آزمون یا همان متغیر <code>prediction</code> نیز مورد بررسی قرار خواهد گرفت و حداقل دقت مورد قبول <span style="color:red"><b>۶۵ درصد</b></span> می‌باشد.
همچنین دیتافریم <code>test_data</code> نیز بررسی و امتیازدهی خواهد شد تا از درستی نحوه‌ی نرمال‌سازی داده‌ها مطمئن شوید.

</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    سلول‌های زیر را به منظور ساخت فایل‌های کلاس‌های پیاده‌سازی شده و پاسخ خود به پرسش مطرح شده اجرا نمایید.
</font>
</p>

In [34]:
from inspect import getsource

inspect_model = Model()

with open("model.py", "w") as f:
    f.write('import numpy as np\n')
    f.write('class Model:\n')
    f.write(getsource(inspect_model.__init__)+'\n')
    f.write(getsource(inspect_model.predict)+'\n')
    f.write(getsource(inspect_model.update_weights_for_one_epoch)+"\n")
    f.write(getsource(inspect_model.fit)+'\n')
f.close()

test_data.to_csv('processed_test_data.csv', index=False)
np.save("prediction.npy", prediction)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد. همچنین اگر از گوگل کولب استفاده می‌کنید، در صورت نیاز به پشتیبانی حتماً آخرین نسخه از نت‌بوک را به‌صورت دستی دانلود کرده و داخل فایل ارسالی قرار دهید یا لینک کولب را با ما به‌اشتراک بگذارید.
</font>
</p>

In [35]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'play_with_shallow.ipynb')):
    %notebook -e play_with_shallow.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['processed_test_data.csv', 'model.py', 'prediction.npy', 'play_with_shallow.ipynb']
compress(file_names)

File Paths:
['processed_test_data.csv', 'model.py', 'prediction.npy', 'play_with_shallow.ipynb']