<a href="https://colab.research.google.com/github/Taheri1400/deep-learning-projects/blob/main/will_not_travel_again.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 dir=rtl align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سفر نمی‌روم دگر!
</font>
</h1>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    احتمالاً هنگامی‌که بخواهید برای تعطیلات نوروز به یک شهر مانند ارومیه سفر کنید، از طریق موبایل و یا لپ‌تاپ‌ و از مسیر جست‌وجوی گوگل، پیامک تبلیغاتی و یا به‌صورت مستقیم، وارد یک سایت رزرو هتل می‌شوید و بعد از ساخت حساب کاربری، اقدام به جست‌وجو کرده و مقصد و تاریخ ورود/خروج خود را وارد می‌کنید. در نتیجه لیستی از هتل‌ها برای شما، نشان داده‌ می‌شود و در نهایت، شما با کلیک بر روی هتل‌های مختلف، اقدام به مقایسه ی آن‌ها کرده و شاید (🙃) در نهایت یکی از آن‌ها را رزرو کنید.
<br>
در این پروژه شما پس از پیش‌پردازش داده‌ها و حل چالش‌های مربوط به آن، مدلی را آموزش می‌دهید که بر اساس اطلاعات جست‌وجوی کاربران و سایر ویژگی‌های مرتبط با آن، بتواند پیش‌بینی کند که آیا یک کاربر، هتل مشاهده‌شده را رزرو خواهد کرد یا خیر. بدین ترتیب، می‌توان در لحظه برای هر کاربر، متناسب با پیش‌بینی رزرو، تصمیم متناسبی همانند ارائه‌ی تخفیف و یا پیشنهاد سایر هتل‌ها اتخاذ کرد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیاز را وارد کنید. در صورتی‌که نیاز به کتابخانه‌های دیگری دارید نیز می‌توانید آن‌ها را فراخوانی کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# !pip install keras --upgrade
# Uncomment the above line if you don't have keras 3 installed

In [2]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

In [3]:
import keras
print(keras.__version__)

3.13.2

In [5]:
import shutil
shutil.unpack_archive("/content/will_not_travel_again_data.zip", "/content/")

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>



<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
به‌دلیل حجم بالای مجموعه‌داده نیاز است آن را جداگانه از <a href="https://drive.google.com/file/d/1jIl8uXsrdRz3ZBxljjQNo0ssDT8LbJBx/view?usp=sharing" target="_blank">این لینک</a> دانلود کرده و فایل‌های داخل آن را استخراج کنید.  توجه داشته باشید که اندازه‌ی مجموعه‌داده حدود ۱۸۰ مگابایت است و اگر قصد دانلود این حجم از داده را ندارید پیشنهاد می‌کنیم از محیط گوگل کولب استفاده کرده و به‌صورت مستقیم با دستور زیر این فایل را روی کولب خود بارگیری کنید.
</font>
</p>

`!gdown 1jIl8uXsrdRz3ZBxljjQNo0ssDT8LbJBx`

<details dir="rtl" style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<summary dir="rtl" style="color:orange"><b>رفع مشکل عدم امکان دانلود فایل با <code>gdown</code></b></summary>

اگر در هنگام دانلود فایل به‌کمک <code>gdown</code> با خطای عدم اجازه‌ی دسترسی مواجه شدید، کافیست کد زیر را اجرا کرده و دوباره امتحان کنید.

<span dir=ltr style="direction:ltr;">

`!pip install --upgrade --no-cache-dir gdown`

</span>
</details>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
در این سوال، شما به داده‌های جست‌وجوی کاربران دسترسی دارید. فایل آموزش (<code>train.csv</code>)، نتایج جست‌وجوی کاربران را در یک بازه‌ی حدوداً دو ساله شامل می‌شود و حدود ۷ میلیون سطر دارد. فایل آزمون (<code>test.csv</code>) دارای ۳۰۰ هزار سطر از اطلاعات جست‌وجوی کاربران در بازه‌ی حدود ۱ ماه پس از آخرین جست‌وجوی موجود در فایل آموزش است (این سطرها، به‌صورت تصادفی از بین چند میلیون سطر آن ماه، انتخاب شده‌اند).
جدول زیر، ستون‌های موجود در فایل آموزش را توضیح می‌دهد. توجه داشته‌ باشید که هر ردیف این مجموعه‌داده، نشان‌دهنده‌ی جست‌وجوی یک کاربر جهت رزرو هتل است.
     همچنین در مجموعه‌داده‌ی آزمون، ستون <code>is_booking</code> وجود ندارد، زیرا در ادامه از این ستون برای ساخت متغیر هدف مسئله استفاده خواهیم کرد.
    <br> نحوه‌ی روبه‌رو شدن شما با مجموعه‌داده‌ای با این حجم، جزو یکی از چالش‌ها و اهداف طراحی این تمرین بوده‌است.

</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| نام ستون | توضیحات ستون |
|:----------:|:------------------:|
| <code>user</code> | شناسه کاربر |
| <code>user_location_country</code> | شناسه‌ی کشور کاربر |
| <code>user_location_region</code> | شناسه‌ی منطقه‌ی کاربر |
| <code>user_location_city</code> | شناسه‌ی شهر کاربر |
| <code>destination_distance</code> | فاصله‌ی فیزیکی بین کاربر و هتل در زمان جست‌وجو‌ (مقدار <code>null</code> به معنی عدم توانایی محاسبه فاصله است) |
| <code>search_date</code> | زمان انجام جست‌وجو |
| <code>is_mobile</code> | آیا کاربر با دستگاه موبایل جست‌وجو انجام داده است؟ |
| <code>is_package</code> | آیا کاربر در حال جست‌وجوی هتل به‌همراه بلیط حمل‌و‌نقل (اتوبوس، هواپیما یا قطار) است؟|
| <code>channel</code> | کاربر از چه کانالی وارد سایت شده‌است؟ (تبلیغات پیامکی، تبلیغات شبکه‌ی اجتماعی، ورود مستقیم و ...)  |
| <code>Search_count</code> |تعداد جست‌وجو‌های مشابه در لحظه‌ی کاربر (در همان نشست یا ‌<i>session</i>)|
| <code>checkIn_date</code> | تاریخ ورود به هتل |
| <code>checkOut_date</code> | تاریخ خروج از هتل |
| <code>n_adults</code> | تعداد افراد بالغ اعلام‌شده جهت رزرو هتل |
| <code>n_children</code> | تعداد کودکان اعلام‌شده جهت رزرو هتل |
| <code>n_rooms</code> | تعداد اتاق مورد نظر برای رزرو |
| <code>destination</code> | شناسه‌ی محل هتل مورد نظر کاربر (با هم‌پوشانی همچون نیویورک، نیویورک سیتی، سنترال پارک و غیره) |
| <code>destination_type</code> | کد نوع هتل مورد نظر کار‌بر |
| <code>hotel_continent</code> | شناسه‌ی قاره‌ی هتل مورد نظر کاربر |
| <code>hotel_country</code> | شناسه‌ی کشور هتل مورد نظر کاربر |
| <code>hotel_market</code> | ناحیه‌ای که هتل مورد نظر کاربر در آن قرار گرفته‌است (بدون هم‌پوشانی همچون نیویورک، بوستون و غیره)|
| <code>hotel_category</code> | گرو‌ه‌بندی هتلی که جزییاتش را مشاهده می‌کنند. این گروه‌بندی می‌تواند بر اساس مواردی مانند چندستاره بودن و یا نوع هتل باشد. |
| <code>is_booking<code> | آیا کاربر در نهایت، هتل مشاهده‌شده را رزرو کرده یا خیر؟ |


</font>
</div>
</center>

In [4]:
!pip install --upgrade --no-cache-dir gdown
!gdown 1jIl8uXsrdRz3ZBxljjQNo0ssDT8LbJBx

Requirement already satisfied: gdown in /usr/local/lib/python3.13/dist-packages (6.4.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from gdown) (4.0.7)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.13/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from gdown) (2.5.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2026.7.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (1.7.1)
Using cookies from /root/.cache/gdown/cookies.txt
Downloading...
From (original): https://drive.google.com/uc?id=1jIl8uXsrdRz3ZBxljjQNo0ssDT8LbJBx
From (redirected): https://drive.google.com/uc?id=1jIl8uXsrdRz3ZBxljjQNo0ssDT8LbJBx&confirm=t&uuid=06b1eeb8-1706-4046-ac01-17aac9bc932b
To: /content/will_not_travel_again_data.zip
100% 188M/188M [00:03<00:00, 62.3MB/s]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خوانش مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
   در ابتدا نیاز است فایل‌ مجموعه‌داده را بخوانید. داده‌‌های آموزش را می‌توانید از فایل <code>train.csv</code> موجود در پوشه‌ی <code>data</code> بخوانید و از نمونه‌های موجود در آن برای آموزش مدل استفاده کنید.
 عملکرد مدل شما روی داده‌ی <code>test.csv</code> برسی می‌شود.
</font>
</p>

In [6]:
!unzip will_not_travel_again_data.zip

Archive:  will_not_travel_again_data.zip
replace data/test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: data/test.csv
replace data/train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: data/train.csv          y

In [3]:
import pandas as pd
import gc

train = pd.read_csv(
    'data/train.csv',
    engine='pyarrow'
)

test = pd.read_csv(
    'data/test.csv',
    engine='pyarrow'
)

In [3]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

train.head()

,user,user_location_country,user_location_region,user_location_city,destination_distance,search_date,is_mobile,is_package,channel,search_count,...,n_adults,n_children,n_rooms,destination,destination_type,hotel_continent,hotel_country,hotel_market,hotel_category,is_booking
0,461899,3,50,5703,NaN,2013-01-07 00:00:02,0,0,9,1,...,2,1,1,669,3,2,50,212,41,0
1,13796,66,174,21177,5713.6206,2013-01-07 00:00:06,0,0,9,3,...,1,0,1,8821,1,6,17,30,58,0
2,1128575,205,155,14703,795.7298,2013-01-07 00:00:06,0,0,9,1,...,1,0,1,25064,6,2,50,1230,91,0
3,1080476,69,761,41949,NaN,2013-01-07 00:00:17,0,1,9,1,...,2,0,1,7635,3,2,50,675,10,0
4,1080476,69,761,41949,NaN,2013-01-07 00:00:23,0,1,9,1,...,2,0,1,7635,3,2,50,675,10,0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
اکتشاف داده‌ها و مهندسی ویژکی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در مرحله اول به بررسی و اکتشاف داده‌ها و مهندسی ویژگی می‌پردازیم. در ابتدا با حذف ستون  <code>user</code> سعی در کم‌کردن حجم داده‌ها می‌کنیم، این عمل با توجه به یکتایی این مقادیر تاثیری در عملکرد مدل نخواهد داشت.
</font>
</p>

In [4]:
train=train.drop(['user'],axis=1)
test=test.drop(['user'],axis=1)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
حذف مقادیر گم‌شده
</font>
</h3>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
   ابتدا با بررسی مقادیر گم‌شده در ستون‌های <code>checkIn_date</code> و <code>checkOut_date</code> این مقادیر را مدیریت کنید. در صورتی‌که حداقل ۹۹ درصد نمونه‌های شامل مقادیر گم‌شده در هر ستون دارای <b style="color:#0099cc">متغیر هدف</b> با مقدار <code>0</code> باشند، آن‌ها را حذف کنید، در غیر این‌صورت از روشی دیگری جهت مدیریت آن‌ها بهره ببرید.
</font>
</p>

In [8]:
train.isnull().sum()/len(train)*100

user_location_country     0.000000
user_location_region      0.000000
user_location_city        0.000000
destination_distance     35.776033
search_date               0.000000
is_mobile                 0.000000
is_package                0.000000
channel                   0.000000
search_count              0.000000
checkIn_date              0.187485
checkOut_date             0.187485
n_adults                  0.000000
n_children                0.000000
n_rooms                   0.000000
destination               0.000000
destination_type          0.000000
hotel_continent           0.000000
hotel_country             0.000000
hotel_market              0.000000
hotel_category            0.000000
is_booking                0.000000
dtype: float64

In [6]:
train[train['checkIn_date'].isnull()]['is_booking'].value_counts(normalize=True)*100

is_booking
0    100.0
Name: proportion, dtype: float64

In [7]:
train[train['checkOut_date'].isnull()]['is_booking'].value_counts(normalize=True)*100

is_booking
0    100.0
Name: proportion, dtype: float64

In [5]:
train=train.dropna(subset=['checkIn_date','checkOut_date'])

In [9]:
train[['checkIn_date', 'checkOut_date']].isnull().sum()

checkIn_date     0
checkOut_date    0
dtype: int64

In [11]:
train.isnull().sum()/len(train)*100

user_location_country     0.000000
user_location_region      0.000000
user_location_city        0.000000
destination_distance     35.762695
search_date               0.000000
is_mobile                 0.000000
is_package                0.000000
channel                   0.000000
search_count              0.000000
checkIn_date              0.000000
checkOut_date             0.000000
n_adults                  0.000000
n_children                0.000000
n_rooms                   0.000000
destination               0.000000
destination_type          0.000000
hotel_continent           0.000000
hotel_country             0.000000
hotel_market              0.000000
hotel_category            0.000000
is_booking                0.000000
dtype: float64


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
همان‌طور که در توضیحات ستون‌های مسئله دیدیم ستون <code>destination_distance</code> فاصله‌ی فیزیکی بین کاربر و هتل در زمان جست‌وجو‌ را نشان می‌دهد. از آنجایی که می‌توانیم بگوییم فاصله‌ی محاسبه‌شده دو شهر با یکدیگر همواره ثابت یا در یک محدوده است، برای پر کردن مقادیر گم‌شده‌ای که این فاصله را نشان می‌دهد، می‌توانیم از <code>user_location_city</code> و <code>destination</code> که بیانگر شناسه‌ی شهر کاربر و هتل جست‌وجو شده هستند، استفاده کنیم به‌طوری‌که نمونه‌‌های که ستون‌ <code>destination_distance</code> در آن گم‌شده است، با را با میانگین مقدار  <code>destination_distance</code> در ستون‌هایی که <code>user_location_city</code> و <code>destination</code> مشابه دارند پر کنیم.
</font>
</p>

In [8]:
train.isna().mean()['destination_distance']

np.float64(0.35762694533684297)

In [6]:
mean = train.groupby(['user_location_city','destination'])['destination_distance'].transform('mean')
mean_distance = train.groupby(
    ['user_location_city', 'destination']
)['destination_distance'].mean()
train['destination_distance'].fillna(mean) #TODO
test_mean = test.set_index(
    ['user_location_city', 'destination']
).index.map(mean_distance)

test_mean = pd.Series(test_mean, index=test.index)

test['destination_distance'] = test['destination_distance'].fillna(test_mean)


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
حال برای سایر موارد گم‌شده از عددی مانند <code>0</code> که در این ستون استفاده نشده است، استفاده می‌کنیم.
</font>
</p>

In [10]:
train[train['destination_distance'] == 0]

Empty DataFrame
Columns: [user_location_country, user_location_region, user_location_city, destination_distance, search_date, is_mobile, is_package, channel, search_count, checkIn_date, checkOut_date, n_adults, n_children, n_rooms, destination, destination_type, hotel_continent, hotel_country, hotel_market, hotel_category, is_booking]
Index: []

[0 rows x 21 columns]

In [7]:
train['destination_distance']=train['destination_distance'].fillna(0) #TODO
test['destination_distance']=test['destination_distance'].fillna(0) #TODO

In [9]:
train.isna().sum()

user_location_country    0
user_location_region     0
user_location_city       0
destination_distance     0
search_date              0
is_mobile                0
is_package               0
channel                  0
search_count             0
checkIn_date             0
checkOut_date            0
n_adults                 0
n_children               0
n_rooms                  0
destination              0
destination_type         0
hotel_continent          0
hotel_country            0
hotel_market             0
hotel_category           0
is_booking               0
dtype: int64

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ویژگی‌های زمانی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
با بررسی ستون‌های مجموعه‌داده مشاهده می‌کنیم که سه ستون <code>checkOut_date</code>، <code>checkIn_date</code> و <code>search_date</code> بیانگر زمان هستند و می‌توان با تبدیل این مقادیر به <code>datetime64[ns]</code>  از آن‌ها اطلاعات و حتی ویژگی‌های جدید و مناسبی استخراج کرد. برای این‌کار از دستور زیر استفاده کنید. البته اکیداً توصیه می‌شود مستندات مربوط به کار با این نوع داده‌ها را بررسی کنید.
</font>
    
```python
df[‘time_type’] = pd.to_datetime(df[‘time_string’])
```
</p>

In [8]:
# TODO : change type of columns in time_columns into datetime64[ns]

time_columns = ['search_date', 'checkIn_date', 'checkOut_date']
for col in time_columns:
  train[col]=pd.to_datetime(train[col])
  test[col]=pd.to_datetime(test[col])


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ابتدا شاید این سه ستون زمانی اطلاعات خوبی به مدل ندهند اما با بررسی دقیق‌تر می‌توانیم دو ویژگی جدید که تعیین‌کننده‌ی  <b>تعداد روز‌های بین زمان جست‌وجو و زمان تعیین‌شده برای ورود</b> و همچنین <b>تعداد روز‌های اقامت تعیین‌شده در جست‌وجو</b> هستند را به مجموعه داده اضافه کنیم.
</font>
</p>

In [9]:
# TODO : Add Days of Stay

duration = (train['checkOut_date']-train['checkIn_date']).dt.days
train['duration'] = duration # TODO
duration = (test['checkOut_date']-test['checkIn_date']).dt.days # TODO
test['duration'] = duration # TODO

# TODO : Add Days between search_date and checkIn_date

days_between = (train['checkIn_date'] - train['search_date']).dt.days
train['days_between'] =days_between # TODO
days_between = (test['checkIn_date'] - test['search_date']).dt.days # TODO
test['days_between'] = days_between # TODO

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
همچنین می‌توانیم با بررسی ساعت، شماره روز‌ هفته و ماه زمان جست‌وجو و ورود به هتل، ارتباط آن‌ها را با رزرو هتل بررسی کنیم. بنابراین ستونی‌های جدول زیر را به مجموعه‌داده اضافه کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| نام ستون | توضیحات ستون |
|:-:|:-:|
|<code>search_date_hour</code>|ساعت جست‌وجو |
|<code>search_date_dayofweek</code>|روز جست‌وجو در هفته|
|<code>checkIn_date_dayofweek</code>|روز ورود در هفته|
|<code>search_date_month</code>|ماه جست‌وجو|
|<code>checkIn_date_month</code>|ماه ورود|

</font>
</div>
</center>

In [10]:
train['search_date_hour'] = train['search_date'].dt.hour # TODO
train['search_date_dayofweek'] = train['search_date'].dt.dayofweek

train['checkIn_date_dayofweek'] = train['checkIn_date'].dt.dayofweek

train['search_date_month'] = train['search_date'].dt.month

train['checkIn_date_month'] = train['checkIn_date'].dt.month

test['search_date_hour'] = test['search_date'].dt.hour

test['search_date_dayofweek'] = test['search_date'].dt.dayofweek

test['checkIn_date_dayofweek'] = test['checkIn_date'].dt.dayofweek

test['search_date_month'] = test['search_date'].dt.month

test['checkIn_date_month'] = test['checkIn_date'].dt.month

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
 حال برای ‌بررسی رابطه‌ی بین ویژگی‌هایی که در مرحله قبل به‌دست آوردیم با متغیر هدف (این‌که جست‌وجو به رزرو هتل منجر شده‌است یا خیر) دو دیتافرم <code>is_booked</code> و <code>not_booked</code> را براساس مجموعه‌داده‌ی آموزش ایجاد کنید، به‌طوری‌که دیتافرم اول فقط نمونه‌هایی که به رزرو ختم شده‌اند و دیتافریم دوم فقط نمونه‌هایی که به رزرو ختم نشده‌اند را شامل شود.
</font>
</p>

In [13]:
is_booked = train[train['is_booking']==1]
not_booked = train[train['is_booking']==0]

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مصورسازی ۱
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
اکنون بیاید با استفاده از مصورسازی، بینش‌های بیشتری را از دل این داده‌ها استخراج کنیم.
در این مرحله نیاز است یک نمودار میله‌ای رسم کنید تا رابطه‌ی بین درصد جست‌وجو‌هایی که به رزرو هتل ختم شده‌اند و نشده‌اند‌ (هر کدام نسبت به دسته‌ی خودشان) در ساعات مختلف را نشان دهد.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
خروجی نمودار شما باید شبیه به تصویر زیر باشد.
</font>
</p>

<center>
<img src = 'https://quera.org/qbox/view/6TWauQwG58/search_hour.png'>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
<b style="color:red; bold">توجه:</b>
لطفا پیش از انجام مصورسازی‌ها به قسمت چالش‌های حل تمرین، باکس "چرا نمودارهایم اشتباه است؟" مراجعه کنید.
</font>
</p>

In [14]:
import plotly.graph_objects as go



not_booked_percentage = (
    not_booked.groupby('search_date_hour').size()
    / len(not_booked)
).sort_index()

is_booked_percentage = (
    is_booked.groupby('search_date_hour').size()
    / len(is_booked)
).sort_index()

trace_not_booked = go.Bar(
    y=not_booked_percentage,
    name='Not Booked'
)

trace_is_booked = go.Bar(
    y=is_booked_percentage,
    name='Booked'
)

# در ادامه‌ی این قسمت از کد تغییری ایجاد نکنید زیرا نمودار شما توسط سیستم داوری بررسی می‌شود و تغییر در این قسمت ممکن است باعث عدم داوری صحیح شود

data = [trace_is_booked, trace_not_booked]

layout = go.Layout(
    xaxis=dict(title='Search Hour', tickangle=45, automargin=True),
    yaxis=dict(title='Frequency')
)

fig = go.Figure(data=data, layout=layout)
fig.show()
fig.write_json('./search_hour.json')


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
در این مرحله می‌توانید با توجه به زمان‌های مختلفی که جست‌وجو در آن انجام شده و رابطه‌ی بین آن با رزرو هتل، مقادیر این ستون را به دسته‌های کوچک‌تری افراز کنید (binning).
          به‌طور مثال به نمونه‌هایی که در آن‌ها جست‌وجو بین ساعت ۵ تا ۱۵ انجام شده‌است، مقدار <code>1</code>
          </font> دهید و به بقیه نمونه‌ها مقدار  <code>0</code> دهید. این عمل یک نوع مهندسی ویژگی به شمار می‌آید. توجه کنید این دسته‌بندی اختیاری بوده است و به‌طور مستقیم داوری نمی‌شود، اما ممکن است در عملکرد مدل شما تاثیر (مثبت یا منفی!) بگذارد، همچنین برای سایر ستون‌ها و ویژگی‌ها نیز با خلاقیت خودتان می‌توانید ویژگی‌های جدیدی خلق کنید.
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مصورسازی ۲
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
همانند نمودار قبل برای روز ورود به هتل  نیز نمودار را رسم کنید. دقت داشته باشید روز‌های هفته به‌صورت، دوشنبه، سه‌شنبه تا شنبه و به همین ترتیب باشد. به رعایت نیم‌فاصله در اسامی روزها توجه داشته باشید. کلمه‌ی سه‌شنبه و پنج‌شنبه دارای نیم‌فاصله است.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
خروجی نمودار شما باید به‌صورت زیر باشد.
</font>
</p>

<center>
<img src = 'https://quera.org/qbox/view/jqISJX07yD/checkIn_day.png'>
</center>

In [15]:
not_booked_frequency = (
    not_booked.groupby('checkIn_date_dayofweek').size()
    / len(not_booked)
).sort_index()

is_booked_frequency = (
    is_booked.groupby('checkIn_date_dayofweek').size()
    / len(is_booked)
).sort_index()



trace_not_booked = go.Bar(y=not_booked_frequency , name='Not Booked') # TODO
trace_is_booked = go.Bar(y=is_booked_frequency , name='Booked') # TODO

ticktext =[
    'دوشنبه',
    'سه‌شنبه',
    'چهارشنبه',
    'پنج‌شنبه',
    'جمعه',
    'شنبه',
    'یکشنبه'
] # TODO

# در ادامه‌ی این قسمت از کد تغییری ایجاد نکنید زیرا نمودار شما توسط سیستم داوری بررسی می‌شود و تغییر در این قسمت ممکن است باعث عدم داوری صحیح شود

data = [trace_is_booked, trace_not_booked]

layout = go.Layout(
    xaxis=dict(title='Day of Week', tickangle=45, automargin=True,
               tickvals = [0,1,2,3,4,5,6], ticktext= ticktext
 ),
    yaxis=dict(title='Frequency'),
)

fig = go.Figure(data=data, layout=layout)
fig.show()
fig.write_json('./checkIn_day.json')

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مصورسازی ۳
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
همانند نمودار قبل برای ماه ورود نیز نمودار را رسم کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
خروجی نمودار شما باید مشابه با تصویر زیر باشد.
</font>
</p>

<center>
<img src = 'https://quera.org/qbox/view/vdWwvplc3K/checkIn_date_month.png'>
</center>

In [23]:
train['checkIn_date_month'].unique()

array([ 3,  1,  5,  4,  2,  9,  6,  7,  8, 11, 10, 12], dtype=int32)

In [16]:
train['checkIn_date_month'] = train['checkIn_date'].dt.month - 1
test['checkIn_date_month'] = test['checkIn_date'].dt.month - 1

not_booked_frequency = (
    not_booked.groupby('checkIn_date_month').size()
    / len(not_booked)
).sort_index()

is_booked_frequency = (
    is_booked.groupby('checkIn_date_month').size()
    / len(is_booked)
).sort_index()



trace_not_booked = go.Bar(y = not_booked_frequency , name='Not Booked') # TODO
trace_is_booked = go.Bar(y = is_booked_frequency , name='Booked') # TODO

# در ادامه‌ی این قسمت از کد تغییری ایجاد نکنید زیرا نمودار شما توسط سیستم داوری بررسی می‌شود و تغییر در این قسمت ممکن است باعث عدم داوری صحیح شود

data = [trace_is_booked, trace_not_booked]

ticktext = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

layout = go.Layout(
    xaxis=dict(title='Month', tickangle=45, automargin=True,
             ticktext = ticktext ,tickvals = np.arange(0,12)),
    yaxis=dict(title='Frequency')
)

fig = go.Figure(data=data, layout=layout)
fig.show()
fig.write_json('./checkIn_date_month.json')


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
در صورت علاقه می‌توانید ماه‌های سال را به فصل نیز تبدیل کنید (مانند پیشنهادی که برای ساعت جست‌وجو داده شد).
</p>

In [ ]:
# TODO (Optional): Make season column for checkIn_date_month or search_date_month

no<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مصورسازی ۴
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
نمودار خطی برای فاصله‌ی زمانی بین جست‌وجو و ورود را نیز رسم کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
خروجی نمودار شما باید به صورت زیر باشد.
</font>
</p>
<center>
<img src = 'https://quera.org/qbox/view/mEwuo0YTeE/days_between.png'>
</center>

In [17]:


not_booked_frequency = (
    not_booked.groupby('days_between').size()
    / len(not_booked)
).sort_index()

is_booked_frequency = (
    is_booked.groupby('days_between').size()
    / len(is_booked)
).sort_index()

trace_not_booked = go.Scatter(y = not_booked_frequency , name='Not Booked', opacity = 0.5) # TODO
trace_is_booked = go.Scatter(y = is_booked_frequency , name='Booked') # TODO

# در ادامه‌ی این قسمت از کد تغییری ایجاد نکنید زیرا نمودار شما توسط سیستم داوری بررسی می‌شود و تغییر در این قسمت ممکن است باعث عدم داوری صحیح شود

data = [trace_is_booked, trace_not_booked]

layout = go.Layout(
    xaxis=dict(title='Days between search and checking time', tickangle=45, automargin=True),
    yaxis=dict(title='Frequency')
)

fig = go.Figure(data=data, layout=layout)
fig.show()
fig.write_json('./days_between.json')

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مصورسازی ۵
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
همچون نمودار بالا یک نمودار برای مدت اقامت نیز رسم کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
خروجی نمودار شما باید به‌صورت زیر باشد.
</font>
</p>

<center>
<img src = 'https://quera.org/qbox/view/iOh4Yzgkf6/los.png'>
</center>

In [18]:
not_booked_frequency = (
    not_booked.groupby('duration').size()
    / len(not_booked)
).sort_index()

is_booked_frequency = (
    is_booked.groupby('duration').size()
    / len(is_booked)
).sort_index()





trace_not_booked = go.Scatter(y = not_booked_frequency , name='Not Booked', opacity = 0.5) # TODO
trace_is_booked = go.Scatter(y = is_booked_frequency , name='Booked') # TODO

# در ادامه‌ی این قسمت از کد تغییری ایجاد نکنید زیرا نمودار شما توسط سیستم داوری بررسی می‌شود و تغییر در این قسمت ممکن است باعث عدم داوری صحیح شود

data = [trace_is_booked, trace_not_booked]

layout = go.Layout(
    xaxis=dict(title='Length of Stay', tickangle=45, automargin=True),
    yaxis=dict(title='Frequency')
)

fig = go.Figure(data=data, layout=layout)
fig.show()
fig.write_json('./los.json')

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خارجی یا داخلی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
تا اینجا داده‌های زمانی را مورد بررسی قرار دادیم و سعی کردیم کمی در آن‌‌ها اکتشاف کنیم.
حال با توجه به داده‌های دیگر می‌توانیم اکتشافات دیگری انجام دهیم. <br>ستونی با نام <code>is_abroad</code> ایجاد کنید و در آن جست‌وجو‌ها برای هتل‌های خارج از کشور کاربر را مشخص کنید.
به‌طور مثال اگر کاربر در کشوری با شناسه‌ی <code>x</code> است و در جست‌وجوی خود هتلی در کشوری غیر از <code>x</code> را جست‌وجو ستون <code>is_abroad</code> را برای این نمونه برابر <code>1</code> قرار دهید.
</font>
</p>

In [17]:
(train['user_location_country'] != train['hotel_country']).astype(int)

0          1
1          1
2          1
3          1
4          1
          ..
7622995    1
7622996    1
7622997    1
7622998    1
7622999    1
Length: 7608708, dtype: int64

In [11]:
# TODO: Add is_abroad column

train['is_abroad'] = (train['user_location_country'] != train['hotel_country']).astype(int)# TODO
test['is_abroad'] = (test['user_location_country'] != test['hotel_country']).astype(int) # TODO

In [20]:
del is_booked, not_booked

In [21]:
import gc
gc.collect()

562

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
🤓 بیشتر
</font>
</h3>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
از آن‌جا که این مجموعه‌داده شامل ویژگی‌های متعدد و متنوعی است، می‌توانید به غیر از موارد خواسته‌شده، از جنبه‌های مختلفی به تحلیل داده‌ها بپردازید. برای مثال می‌توانید توزیع‌های سایر ویژگی‌ها را بررسی کنید، ارتباط ویژگی‌ها با هم و با متغیر هدف را بررسی کنید. همچنین با توجه به بینش‌هایی که از داده‌ها به‌دست می‌آورید، می‌توانید به پیش‌پردازش داده‌ها بپردازید تا ورودی‌های باکیفیت‌تری را برای مدل خود آماده کنید. این بخش به‌صورت جداگانه مورد داوری قرار نمی‌گیرد و دست شما باز است تا از هر تکنیکی که برای بهبود عملکرد مدل خود لازم می‌دانید استفاده کنید.
در انجام مراحل پیش‌پردازش و مهندسی ویژگی، می‌توانید موارد زیر را انجام دهید. همچنین توجه داشته باشید در نهایت مجموعه‌داده آموزش و آزمون باید ساختاری مشابه یکدیگر داشته باشند.

<ul dir=rtl>
<li dir=rtl>
 مدیریت ویژگی‌های دسته‌ای ترتیبی و اسمی (توجه داشته باشید با این‌که داده‌های مجموعه‌داده‌ی اولیه از نوع عدد هستند اما الزاماً اعداد آن‌ها بار معنایی از نظر ریاضی ندارند و با برخی از آن‌ها باید همچون ویژگی‌های دسته‌ای برخورد کنید و شاید برای بهبود مدل نیاز به مدیریت این داده‌ها داشته باشید.)
    </li>
    <li dir=rtl>
        در بعضی موارد حذف بعضی ستون‌ها به بهبود مدل کمک می‌کند، به‌طور مثال در مرحله‌ی قبل ستونی برای خارجی بودن هتل ایجاد کردیم، حال ممکن است دیگر نیازی به کشور کاربر و یا هتل با توجه به ستون جدید نداشته باشیم.
    </li>
       <li dir=rtl>
           با بررسی توزیع مجموعه‌داده متوجه می‌شوید که این مجموعه‌داده متوازن نیست، بنابراین نحوه‌ی مدیریت این چالش نیز می‌تواند در مدل شما تاثیر بگذارد.
    </li>
</ul>
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
توجه داشته باشید که کدنویسی سلول‌های زیر کاملاً اختیاری است.
</font>
</p>

In [ ]:
# TODO: Preprocessing Any Thing You Want

In [12]:
# TODO: Preprocessing (Drop Unnecessary Columns) (Optional)
# TODO: Preprocessing (Drop Unnecessary Columns) (Optional)

columns_to_drop = [
    'search_date',
    'checkIn_date',
    'checkOut_date'
]

train = train.drop(columns=columns_to_drop)
test = test.drop(columns=columns_to_drop)

In [14]:
# TODO: Preprocessing (Make One-hotted Columns) (Optional)

dummy_columns = [
    'is_mobile',
    'is_package',
    'channel',
    'destination_type',
    'hotel_continent',
    'hotel_category',
    'is_abroad'
]

train = pd.get_dummies(train, columns=dummy_columns)
test = pd.get_dummies(test, columns=dummy_columns)

In [13]:
from sklearn.preprocessing import OrdinalEncoder

columns_to_encode = [
    'destination',
    'hotel_market',
    'user_location_country',
    'user_location_region',
    'user_location_city',
    'hotel_country'
]

encoder = OrdinalEncoder(
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

train[columns_to_encode] = encoder.fit_transform(
    train[columns_to_encode]
)

test[columns_to_encode] = encoder.transform(
    test[columns_to_encode]
)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
پس از آماده‌سازی داده‌ها نوبت به ساخت شبکه‌ی عصبی می‌رسد. باز هم دست‌تان باز است تا معماری موردنظر خود را طراحی کنید و از هر تکنیکی که لازم می‌دانید جهت بهتر کردن فرآیند آموزش مدل استفاده کنید. پیشنهاد می‌کنیم تکنیک‌های مختلفی که تا اینجای دوره آموخته‌اید را آزمایش کرده و به تفسیر نتایج بپردازید.
دقت داشته باشید در خروجی مدل باید احتمال رزرو شدن هتل را پیش‌بینی کنید. به عبارت بهتر احتمال <code>1</code>
 شدن ستون <code>is_booking</code>
 را تخمین بزنید.
همچنین توجه داشته باشید که برای ارزیابی مدل شما از معیار <code>AUC</code> یعنی سطح زیر منحنی نمودار <code>ROC</code> استفاده می‌شود. برای مطالعه بیشتر در مورد این نمودار می‌توانید <a href = 'https://en.wikipedia.org/wiki/Receiver_operating_characteristic'> ویکی‌پدیا </a>
    یا <a href = 'https://stanford.edu/~shervine/l/fa/teaching/cs-229/cheatsheet-machine-learning-tips-and-tricks'> راهنمای کوتاه نکات و ترفندهای یادگیری ماشین </a>
 را مطالعه کنید.
</font>
</p>

In [14]:
X = train.drop(columns=['is_booking'])
y = train['is_booking']

In [15]:
from sklearn.preprocessing import StandardScaler

X = X.astype('float32')

scaler = StandardScaler()

X = scaler.fit_transform(X)

In [16]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Input(shape=(X.shape[1],)),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.2),

    keras.layers.Dense(1, activation='sigmoid')
])

In [17]:
# TODO : Complie the Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['AUC']
)

In [18]:
# TODO : Train your Model

epochs = 6 # TODO
BATCH_SIZE = 1024 # TODO

checkpoint_cb = None # TODO (Optional)

history = model.fit(X,
    y,
    epochs=epochs,
    batch_size=BATCH_SIZE) #TODO

Epoch 1/6
7431/7431 ━━━━━━━━━━━━━━━━━━━━ 64s 8ms/step - AUC: 0.7435 - loss: 0.2625
Epoch 2/6
7431/7431 ━━━━━━━━━━━━━━━━━━━━ 59s 8ms/step - AUC: 0.7583 - loss: 0.2579
Epoch 3/6
7431/7431 ━━━━━━━━━━━━━━━━━━━━ 59s 8ms/step - AUC: 0.7606 - loss: 0.2572
Epoch 4/6
7431/7431 ━━━━━━━━━━━━━━━━━━━━ 63s 8ms/step - AUC: 0.7619 - loss: 0.2568
Epoch 5/6
7431/7431 ━━━━━━━━━━━━━━━━━━━━ 64s 9ms/step - AUC: 0.7626 - loss: 0.2566
Epoch 6/6
7431/7431 ━━━━━━━━━━━━━━━━━━━━ 58s 8ms/step - AUC: 0.7632 - loss: 0.2564

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌بینی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در فایل <code>test.csv</code> لیستی از نمونه‌های آزمون در اختیار شما قرار گرفته و نیاز است به‌ازای هر کدام از آن‌ها احتمال رزرو هتل را پیش‌بینی کنید. پیشنهاد می‌کنیم برای اطمینان از عملکرد مدل خود و بهبود آن، ابتدا آن را بر روی یک مجموعه‌ی اعتبارسنجی آزمایش کنید.
</font>
</p>


<h3 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
برای ارزیابی عملکرد مدل شما بر روی نمونه‌های آزمون از معیار <code>AUC</code> نمودار <code>ROC</code> استفاده می‌کنیم.
</font>
</p>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>74.00</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

In [19]:
from sklearn.metrics import roc_auc_score
y_pred = model.predict(X).ravel()

auc = roc_auc_score(y, y_pred)

print("Validation AUC:", auc)

237773/237773 ━━━━━━━━━━━━━━━━━━━━ 288s 1ms/step
Validation AUC: 0.7678897364435802

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ساختار خروجی برای نمونه‌های آزمون
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
اکنون نیاز است به‌ازای هر نمونه‌ی آزمون <b style="color:#0099cc">احتمال</b> رزرو هتل را پیش‌بینی کنید.
 پیش‌بینی مدل خود را برای نمونه‌های آزمون تولید کرده و در ستون <code>prediction</code> دیتافریمی با نام <code>submission</code> ذخیره کنید. توجه داشته باشید که ترتیب مقادیر این ستون باید دقیقاً معادل با ترتیب نمونه‌های آزمون باشد. به این معنی که  ردیف i ام ستون <code>submission</code>، پیش‌بینی شما برای سطر ردیف <code>i</code> ام فایل آزمون باشد (دقت کنید که این ستون باید حتماً دارای <code>header</code> باشد).  همچنین از آنجایی که این ستون بیانگر احتمال است مقادیر این ستون باید مقداری <b>بین</b> <code>0</code> تا <code>1</code> باشد.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
یک نمونه‌ی فرضی از دیتافریم <code>submission</code> در جدول زیر نمایش داده شده است.
 </font>
</p>
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

|<code>prediction</code>|
|:------:|
|0.723|
|0.516|
|0.281|
| ... |

    
</font>
</div>
</center>

In [28]:
test = test.drop(columns=[''])

In [29]:
test = scaler.transform(test)

In [30]:
# Preparing Submission Dataframe
prediction=model.predict(test).ravel()
submission = pd.DataFrame({'prediction':prediction})

10182/10182 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

In [31]:
submission.head()

   prediction
0    0.097362
1    0.175744
2    0.147257
3    0.267658
4    0.089875

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد. همچنین اگر از گوگل کولب استفاده می‌کنید، در صورت نیاز به پشتیبانی حتماً آخرین نسخه از نت‌بوک را به‌صورت دستی دانلود کرده و داخل فایل ارسالی قرار دهید یا لینک کولب را با ما به‌اشتراک بگذارید.
</font>
</p>

In [32]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'will_not_travel_again.ipynb')):
    %notebook -e will_not_travel_again.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['will_not_travel_again.ipynb', 'submission.csv',
              'search_hour.json', 'checkIn_date_month.json',
              'checkIn_day.json', 'days_between.json', 'los.json']
compress(file_names)

File Paths:
['will_not_travel_again.ipynb', 'submission.csv', 'search_hour.json', 'checkIn_date_month.json', 'checkIn_day.json', 'days_between.json', 'los.json']